server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server: 
        git: 
          #github仓库的路径，即去这个仓库里面找我们对应的配置文件.
          uri: git@github.com:wangziqi6855/microservicecloud-config.git